### ISSUE TITLE
Feature Request: Homeassistant Toggle for Lyrics

### ISSUE THREAD

**Issue by Porco-Rosso** [idodov/pixoo64-media-album-art#10]
At the moment the only way to enable or disable lyrics display is to edit the apps.yaml file.

It would be great if we could toggle some of the features, notably the lyrics display attribute from home assistant.
In the same vein as the `input_boolean.pixoo64_album_art` we could have a `input_boolean.pixoo64_lyrics`

I know this complicates setup, so perhaps it could be optional, defined in the apps.yaml

Some other toggles good toggles to consider would be: 
- The light and WLED integration
- Special mode / clock
- show_text

**Comment by idodov** [comment]
Thank you for your suggestion! You made a great point about improving the user-friendliness of configuring display features.

As a result, I’ve introduced a new option using the `input_select` entity, which offers a more efficient solution compared to multiple `input_booleans`.

However, I haven’t implemented all of your recommendations just yet, but I hope you’ll find the current setup satisfying!

-----

1. Update the script
2. Add the new input select entity in `configuration.yaml` file (or create it as helper)
```yaml
input_select:
  pixoo64_album_art_display_mode:
    name: Pixoo64 Display Mode
    icon: mdi:application-cog
    options:
      - "Default"
      - "AI Generation"
      - "Clock only"
      - "Clock and Temperature"
      - "Clock Temperature and Text"
      - "Clock Temperature and Text with Background"
      - "Text only"
      - "Text with Background"
      - "Temperature only"
      - "Temperature and Text"
      - "Temperature and Text with Background"
      - "Lyrics"
      - "Lyrics with Background"
      - "Special Mode"
      - "Special Mode with Text"
      - "Spotify Slider"
    initial: "Default"
```
3. Restart Home Assistant
