### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'temperature_ha'

### ISSUE THREAD

**Issue by Noirbonn666** [idodov/pixoo64-media-album-art#8]
Hello,
big thanks to you for providing this!! It is just awesome and works great!
I just see a minor issue in the logs and that looks like this:

                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Config' object has no attribute 'temperature_ha'
2025-03-14 06:42:37,164 INFO pixoo64_media_album_art: Falling back to alternative album art sources for 'Judas Priest - A Touch of Evil'.
2025-03-14 06:42:40,236 INFO pixoo64_media_album_art: Successfully retrieved album art from Spotify.
2025-03-14 06:42:40,660 ERROR pixoo64_media_album_art: Error in _process_and_display_image: 'Config' object has no attribute 'temperature_ha'
Traceback (most recent call last):
  File "/homeassistant/appdaemon/apps/pixoo64-media-album-art/pixoo64_media_album_art.py", line 2980, in _process_and_display_image
    if (self.config.temperature or self.config.temperature_ha) and not self.config.special_mode:
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^

My Config looks like this:
``

--
hello_world:
  module: hello
  class: HelloWorld
pixoo64_media_album_art:
    module: pixoo64_media_album_art
    class: Pixoo64_Media_Album_Art
    home_assistant:
        ha_url: "http://homeassistant.fritz.box:8123"   # Your Home Assistant URL.
        media_player: "media_player.buro"           # The entity ID of your media player.
        toggle: "input_boolean.pixoo64_album_art"   # An input boolean to enable or disable the script's execution.
        pixoo_sensor: "sensor.pixoo64_media_data"   # A sensor to store extracted media data.
        temperature_sensor: "sensor.gw1100a_v2_1_3_outdoor_temperature"   # HomeAssistant Temperature sensor name instead of the Divoom weather.
        light: 
            - "light.mancave_led_2"
            - "light.kopf"                # The entity ID of an RGB light to synchronize with the album art colors.
        ai_fallback: "turbo"                        # The AI model to use for generating alternative album art when needed (supports 'flux' or 'turbo').
        force_ai: False                             # If True, only AI-generated images will be displayed all the time.
        musicbrainz: True                           # If True, attempts to find a fallback image on MusicBrainz if other sources fail.
        spotify_client_id: xxxxx                   # Your Spotify API client ID (needed for Spotify features). Obtain from https://developers.spotify.com.
        spotify_client_secret: xxxxxx             # Your Spotify API client secret (needed for Spotify features).
        tidal_client_id: False                      # Your TIDAL API client ID. Obrain from https://developer.tidal.com/dashboard.
        tidal_client_secret: False                  # Your TIDAL client secret
        last.fm: False                              # Your Last.fm API key. Obtain from https://www.last.fm/api/account/create.
        discogs: False                              # Your Discogs API key. Obtain from https://www.discogs.com/settings/developers.
    pixoo:
        url: "192.168.66.198"                       # The IP address of your Pixoo64 device.
        full_control: False                          # If True, the script will control the Pixoo64's on/off state in sync with the media player's play/pause.
        contrast: True                              # If True, applies a 50% contrast filter to the images displayed on the Pixoo.
        colors: True                               # If True, enhanced colors
        kernel: False                               # If True, add embos/edge effect
        sharpness: False                            # If True, add sharpness efeect
        special_mode: False                         # Show day, time and temperature above in upper bar.
        info: False                                 # Show information while fallback
        clock: False                                 # If True, a clock is displayed in the top corner of the screen.
        clock_align: "Right"                        # Clock alignment: "Left" or "Right".
        tv_icon: False                               # If True, displays a TV icon when audio is playing from a TV source.
        lyrics: False                               # If True, attempts to display lyrics on the Pixoo64 (show_text and clock will be disabled).
        lyrics_font: 2                              # Recommend values: 2, 4, 32, 52, 58, 62, 48, 80, 158, 186, 190, 590. More values can be found at https://app.divoom-gz.com/Device/GetTimeDialFontList (you need ID value)
        limit_colors: False                         # Reduces the number of colors in the picture from 4 to 256, or set it to False for original colors.
        spotify_slide: False                       # If True, forces an album art slide (requires a Spotify client ID and secret). Note: clock and title will be disabled in this mode.
        images_cache: 25                            # The number of processed images to keep in the memory cache. Use wisely to avoid memory issues (each image is approximately 17KB).
        show_text:
            enabled: False                          # If True, displays the artist and title of the current track.
            clean_title: True                       # If True, removes "Remastered," track numbers, and file extensions from the title.
            text_background: True                   # If True, adjusts the background color behind the text for improved visibility.
            special_mode_spotify_slider: False      # Create animation album art slider
        crop_borders:
            enabled: False                           # If True, attempts to crop any borders from the album art.
            extra: False                            # If True, applies an enhanced border cropping algorithm.

Would be nice to know if I just can ignore it or if possible how to remove it ...

cheers
Lars

**Comment by idodov** [comment]
Hello!  
It looks like your `apps.yaml` file is missing a line that enables the alternative temperature sensor. Below is the correct code to resolve the issue.  

```yaml
---
hello_world:
  module: hello
  class: HelloWorld

pixoo64_media_album_art:
  module: pixoo64_media_album_art
  class: Pixoo64_Media_Album_Art
  home_assistant:
    ha_url: "http://homeassistant.fritz.box:8123" # Your Home Assistant URL.
    media_player: "media_player.buro" # The entity ID of your media player.
    toggle: "input_boolean.pixoo64_album_art" # An input boolean to enable or disable the script's execution.
    pixoo_sensor: "sensor.pixoo64_media_data" # A sensor to store extracted media data.
    temperature_sensor: "sensor.gw1100a_v2_1_3_outdoor_temperature" # HomeAssistant Temperature sensor name instead of the Divoom weather.
    light:
    - "light.mancave_led_2"
    - "light.kopf" # The entity ID of an RGB light to synchronize with the album art colors.
  ai_fallback: "turbo" # The AI model to use for generating alternative album art when needed (supports 'flux' or 'turbo').
  force_ai: False # If True, only AI-generated images will be displayed all the time.
  musicbrainz: True # If True, attempts to find a fallback image on MusicBrainz if other sources fail.
  spotify_client_id: False # Your Spotify API client ID (needed for Spotify features). Obtain from https://developers.spotify.com.
  spotify_client_secret: False # Your Spotify API client secret (needed for Spotify features).
  tidal_client_id: False # Your TIDAL API client ID. Obrain from https://developer.tidal.com/dashboard.
  tidal_client_secret: False # Your TIDAL client secret
  last.fm: False # Your Last.fm API key. Obtain from https://www.last.fm/api/account/create.
  discogs: False # Your Discogs API key. Obtain from https://www.discogs.com/settings/developers.
  pixoo:
    url: "192.168.66.198" # The IP address of your Pixoo64 device.
    full_control: False # If True, the script will control the Pixoo64's on/off state in sync with the media player's play/pause.
    contrast: True # If True, applies a 50% contrast filter to the images displayed on the Pixoo.
    colors: True # If True, enhanced colors
    kernel: False # If True, add embos/edge effect
    sharpness: False # If True, add sharpness efeect
    special_mode: False # Show day, time and temperature above in upper bar.
    temperature: True
    info: False # Show information while fallback
    clock: False # If True, a clock is displayed in the top corner of the screen.
    clock_align: "Right" # Clock alignment: "Left" or "Right".
    tv_icon: False # If True, displays a TV icon when audio is playing from a TV source.
    lyrics: False # If True, attempts to display lyrics on the Pixoo64 (show_text and clock will be disabled).
    lyrics_font: 2 # Recommend values: 2, 4, 32, 52, 58, 62, 48, 80, 158, 186, 190, 590. More values can be found at https://app.divoomgz.com/Device/GetTimeDialFontList (you need ID value)
    limit_colors: False # Reduces the number of colors in the picture from 4 to 256, or set it to False for original colors.
    spotify_slide: False # If True, forces an album art slide (requires a Spotify client ID and secret). Note: clock and title will be disabled in this mode.
    images_cache: 25 # The number of processed images to keep in the memory cache. Use wisely to avoid memory issues (each image is approximately 17KB).
    show_text:
      enabled: False # If True, displays the artist and title of the current track.
      clean_title: True # If True, removes "Remastered," track numbers, and file extensions from the title.
      text_background: True # If True, adjusts the background color behind the text for improved visibility.
    special_mode_spotify_slider: False # Create animation album art slider
    crop_borders:
      enabled: False # If True, attempts to crop any borders from the album art.
      extra: False # If True, applies an enhanced border cropping algorithm.
```
